apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  ReclaimPolicy: Retain
  resources:
    requests:
      storage: 10Gi
  nfs:
    server: 192.168.56.1
    path: /mnt/nfs_shared/jenkins