apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  #storageClassName: jenkins-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi