---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.1
    path: /mnt/nfs_shared/jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  storageClassName: jenkins-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-sc
  namespace: jenkins
provisioner: kubernetes.io/no-provisioner
# 스토리지 클래스가 동적 프로비저닝을 지원하지 않을 때 사용하는 옵션
# 이 옵션을 사용하면 PV와 PV 간의 바인딩이 나중에 수행되도록 지정할 수 있다.
volumeBindingMode: WaitForFirstConsumer
parameters:
  server: 192.168.56.1
  path: /mnt/nfs_shared/jenkins