annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added workflow startup option --log-format (defaults to 'text').
    - kind: added
      description: Added server startup option --log-format (defaults to 'text').
    - kind: added
      description: Added server startup option --loglevel (defaults to 'info').
    - kind: added
      description: Added server startup option --gloglevel (defaults to '0').
apiVersion: v2
appVersion: v3.4.5
description: A Helm chart for Argo Workflows
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-workflows
sources:
- https://github.com/argoproj/argo-workflows
type: application
version: 0.22.13
